FROM python:3.11-slim

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY docker/fastapi/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY config/fastapi /app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "10000"]